// Pure publish-plan building (no network / RN deps, so it's unit-testable): turn the
// project's phases.json / issues.json into milestone + issue specs. The network
// orchestrator (publish.ts) consumes this.

import type { PlanProject } from './project';

export interface PublishMilestone { name: string; description?: string }
export interface PublishIssue { title: string; body: string; labels: string[]; milestone?: string }
export interface PublishPlan {
  milestones: PublishMilestone[];
  issues: PublishIssue[];
  warnings: string[];
}

function readContent(project: PlanProject, ...keys: string[]): string | undefined {
  for (const k of keys) {
    if (project.sections[k]) return project.sections[k].content;
    if (project.artifacts[k]) return project.artifacts[k];
  }
  return undefined;
}
function parseArr(content: string | undefined): Record<string, unknown>[] {
  if (!content) return [];
  try {
    const v: unknown = JSON.parse(content);
    return Array.isArray(v) ? v.filter((x): x is Record<string, unknown> => !!x && typeof x === 'object') : [];
  } catch { return []; }
}
function str(v: unknown): string | undefined {
  return typeof v === 'string' && v.trim() ? v.trim() : undefined;
}
function strArr(v: unknown): string[] {
  if (Array.isArray(v)) return v.map((x) => (typeof x === 'string' ? x : String(x))).filter(Boolean);
  const s = str(v);
  return s ? [s] : [];
}

/** Compose a GitHub issue body from the planner's agent-ready issue fields. */
export function buildIssueBody(issue: Record<string, unknown>): string {
  const parts: string[] = [];
  const acceptance = str(issue.acceptance);
  const files = strArr(issue.files);
  const deps = strArr(issue.deps ?? issue.dependencies);
  const stream = str(issue.stream);
  if (acceptance) parts.push(`## Acceptance criteria\n${acceptance}`);
  if (files.length) parts.push(`## Owned files\n${files.map((f) => `- \`${f}\``).join('\n')}`);
  if (deps.length) parts.push(`## Dependencies\n${deps.map((d) => `- ${d}`).join('\n')}`);
  if (stream) parts.push(`**Stream:** ${stream}`);
  parts.push('— Generated by the base-studio-code planner');
  return parts.join('\n\n');
}

/** Build the (pure) publish plan from the project's phases/issues artifacts. */
export function buildPublishPlan(project: PlanProject): PublishPlan {
  const warnings: string[] = [];

  const milestones: PublishMilestone[] = [];
  for (const p of parseArr(readContent(project, 'phases.json', 'phases'))) {
    const name = str(p.name) ?? str(p.title);
    if (!name) continue;
    milestones.push({ name, description: str(p.description) ?? str(p.desc) });
  }
  const milestoneNames = new Set(milestones.map((m) => m.name));

  const issues: PublishIssue[] = [];
  for (const it of parseArr(readContent(project, 'issues.json', 'issues'))) {
    const title = str(it.title);
    if (!title) { warnings.push('Skipped an issue with no title.'); continue; }
    const milestone = str(it.milestone);
    if (milestone && !milestoneNames.has(milestone)) {
      warnings.push(`Issue "${title}" → milestone "${milestone}" isn't in phases.json; it will be created.`);
    }
    if (!str(it.acceptance)) warnings.push(`Issue "${title}" has no acceptance criteria.`);
    issues.push({ title, body: buildIssueBody(it), labels: strArr(it.labels), milestone });
  }
  if (!issues.length) warnings.push('No issues to publish — write issues.json first.');

  return { milestones, issues, warnings };
}

/** "owner/repo" from the plan's repos.json, if present (to prefill the target). */
export function defaultRepoFromPlan(project: PlanProject): string | undefined {
  const first = parseArr(readContent(project, 'repos.json', 'repos'))[0];
  if (!first) return undefined;
  const owner = str(first.owner);
  const repo = str(first.repo);
  if (owner && repo) return `${owner}/${repo}`;
  return str(first.fullName) ?? str(first.full_name);
}
