// Run once: npx tsx src/lib/tunnel/gen-noise-vectors.mts
// Produces src/lib/tunnel/noiseVectors.fixtures.json with pinned Noise IK bytes.
// Fixed key secrets → fixed public keys → deterministic handshake transcript.

import { __setRandomBytesForTest, HandshakeState, generateKeyPair, NoiseSession } from './noise.js';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const __dir = path.dirname(fileURLToPath(import.meta.url));

// Six 32-byte secrets returned in call order:
//   0 → initiator static   (NoiseSession constructor)
//   1 → initiator ephemeral (NoiseSession.startHandshake)
//   2 → responder static   (explicit in test)
//   3 → responder ephemeral (HandshakeState.writeMessage for responder msg2)
const FIXED_SECRETS = [
  new Uint8Array(32).fill(0x01), // initiator static
  new Uint8Array(32).fill(0x02), // initiator ephemeral
  new Uint8Array(32).fill(0x03), // responder static
  new Uint8Array(32).fill(0x04), // responder ephemeral
];
let callIdx = 0;
__setRandomBytesForTest((n) => {
  if (callIdx >= FIXED_SECRETS.length) throw new Error(`unexpected RNG call #${callIdx}`);
  return FIXED_SECRETS[callIdx++].slice(0, n);
});

// ── Build responder keypair first (so its public key is available for initiator) ──
callIdx = 2; // skip to responder static
const responderKp = generateKeyPair();

// ── Run initiator (calls 0 + 1) ──
callIdx = 0;
const b64 = (u8: Uint8Array) => Buffer.from(u8).toString('base64');
const hex  = (u8: Uint8Array) => Buffer.from(u8).toString('hex');
const session = new NoiseSession(responderKp.publicKey);
const msg1 = session.startHandshake();

// ── Run responder (call 3 for ephemeral inside writeMessage) ──
callIdx = 3;
const respHS = new HandshakeState(false, new Uint8Array(0), responderKp, null);
const msg2Payload = respHS.readMessage(msg1);
const msg2 = respHS.writeMessage(new Uint8Array(0));

// ── Complete initiator side (split) ──
session.finishHandshake(msg2);

// ── Verify symmetric channel works ──
// Initiator sends with c1; responder receives with c1.
const plain = new TextEncoder().encode('hello noise');
const ct  = session.encrypt(plain);
const [c1] = respHS.split();
const decrypted = c1.decryptWithAd(new Uint8Array(0), ct);
if (Buffer.from(decrypted).toString() !== 'hello noise') throw new Error('loopback failed');
console.log('Loopback check: OK');

const fixture = {
  _comment: 'Noise_IK_25519_ChaChaPoly_BLAKE2s test vectors — generated by gen-noise-vectors.mts. DO NOT EDIT manually.',
  protocol: 'Noise_IK_25519_ChaChaPoly_BLAKE2s',
  prologue: '',
  initiatorStaticSecret: hex(FIXED_SECRETS[0]),
  initiatorEphemeralSecret: hex(FIXED_SECRETS[1]),
  responderStaticSecret: hex(FIXED_SECRETS[2]),
  responderEphemeralSecret: hex(FIXED_SECRETS[3]),
  msg1Hex: hex(msg1),
  msg1Length: msg1.length,
  msg2Hex: hex(msg2),
  msg2Length: msg2.length,
  msg2ResponderPayload: hex(msg2Payload),
};

const out = path.join(__dir, 'noiseVectors.fixtures.json');
fs.writeFileSync(out, JSON.stringify(fixture, null, 2) + '\n');
console.log(`Wrote ${out}`);
console.log('msg1 length (expect 96):', msg1.length);
console.log('msg2 length (expect 48):', msg2.length);
