// Generates a deterministic Noise IK test vector (cacophony/noise-c format) from
// the JS impl and writes it to src/lib/noise/noise-vectors.json. Fixed static +
// ephemeral keys make every wire byte reproducible, so the desktop's Rust `snow`
// can assert it produces identical bytes — a true cross-impl interop proof with
// no live connection. Run: node --experimental-strip-types scripts/noise-vectors.ts
import { writeFileSync } from 'node:fs';
import { x25519 } from '@noble/curves/ed25519.js';
import {
  createInitiator, HandshakeState, IK_MSG1, IK_MSG2,
  type Keypair, type Rng,
} from '../src/lib/noise/noise.ts';

const hex = (b: Uint8Array) => Buffer.from(b).toString('hex');
const enc = new TextEncoder();

// Deterministic, distinct 32-byte private keys (any 32 bytes are valid X25519).
const fixed = (base: number): Uint8Array =>
  Uint8Array.from({ length: 32 }, (_, i) => (base + i) & 0xff);
const keypair = (priv: Uint8Array): Keypair => ({ priv, pub: x25519.getPublicKey(priv) });
// RNG that always returns the same fixed ephemeral (one per side).
const fixedRng = (priv: Uint8Array): Rng => () => priv.slice();

const initStatic = keypair(fixed(0x01));
const initEphem = fixed(0x40);
const respStatic = keypair(fixed(0x80));
const respEphem = fixed(0xc0);
const PROLOGUE = new Uint8Array(0); // MUST match the desktop's snow prologue.

const payloads = [
  enc.encode('msg1-initiator-payload'),
  enc.encode('msg2-responder-payload'),
  enc.encode('transport c->s #1'),
  enc.encode('transport s->c #1'),
];

const initiator = createInitiator(initStatic, respStatic.pub, fixedRng(initEphem), PROLOGUE);
const responder = new HandshakeState(false, respStatic, null, PROLOGUE, fixedRng(respEphem));

// Handshake
const msg1 = initiator.writeMessage1(payloads[0]);
responder.readMessage(IK_MSG1, msg1, false);
const w2 = responder.writeMessage(IK_MSG2, payloads[1], true);
const r2 = initiator.readMessage2(w2.message);
const initTransport = r2.transport;
const respTransport = w2.split!;

// Transport (alternating, as cacophony vectors do)
const t1 = initTransport.send.encrypt(new Uint8Array(0), payloads[2]);
const t2 = respTransport.send.encrypt(new Uint8Array(0), payloads[3]);

const vector = {
  protocol_name: 'Noise_IK_25519_ChaChaPoly_BLAKE2s',
  comment: 'Generated by mobile-studio-code JS impl. Desktop snow must reproduce these byte-for-byte. prologue is empty — confirm it matches snow.',
  init_prologue: hex(PROLOGUE),
  init_static: hex(initStatic.priv),
  init_ephemeral: hex(initEphem),
  init_remote_static: hex(respStatic.pub),
  resp_static: hex(respStatic.priv),
  resp_ephemeral: hex(respEphem),
  messages: [
    { payload: hex(payloads[0]), ciphertext: hex(msg1) },
    { payload: hex(payloads[1]), ciphertext: hex(w2.message) },
    { payload: hex(payloads[2]), ciphertext: hex(t1) },
    { payload: hex(payloads[3]), ciphertext: hex(t2) },
  ],
};

const out = new URL('../src/lib/noise/noise-vectors.json', import.meta.url);
writeFileSync(out, JSON.stringify(vector, null, 2) + '\n');
console.log('wrote', out.pathname);
console.log('msg1', vector.messages[0].ciphertext.length / 2, 'bytes');
console.log('msg2', vector.messages[1].ciphertext.length / 2, 'bytes');
